name: code-quality
description: Runs Code quality checks

inputs:
  wait:
    required: false
    default: true
  coverage:
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "Placeholder for qualiry check"
      shell: bash
