name: code-quality
description: Runs Code quality checks

inputs:
  wait:
    required: false
    default: false
  coverage_file:
    required: true
  sonar_server:
    required: false
  sonar_token:
    required: true
  github_token:
    required: true
  coverage_dir:
    required: true

runs:
  using: "composite"
  steps:
    - uses: hipagesgroup/actions/github-env-vars-action@master

    - name: Download test coverage data
      uses: actions/download-artifact@v2
      with:
        name: coverage
        path: ${{ inputs.coverage_dir }}
    
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization="${CI_REPOSITORY_OWNER_SLUG}"
          -Dsonar.projectKey="${CI_REPOSITORY_NAME_SLUG}"
          -Dsonar.projectVersion="${CI_SHA_SHORT}"
          -Dsonar.links.scm="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          -Dsonar.links.ci="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          -Dsonar.javascript.lcov.reportPaths="${{ inputs.coverage_dir }}/${{ inputs.coverage_file }}"
          -Dsonar.sources=.
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}

    - name: Check quality gate
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
       SONAR_TOKEN: ${{ inputs.sonar_token }}
      if: ${{ inputs.wait == 'true' }}
