name: code-quality
description: Runs Code quality checks

inputs:
  wait:
    required: false
    default: true
  coverage:
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "Placeholder for qualiry check"
      shell: bash

    - name: Download test coverage data
      uses: actions/download-artifact@v2
      with:
        name: coverage
        path: coverage/

    - name: Check quality gate
      run: echo "Wait for quality gate to pass"
      if: ${{ inputs.wait }}