name: security
description: Performs security checks. for example container scanning and sast

inputs:
  lacework-token:
    description: 'Lacework access token'
    required: true
  github-token:
    description: 'Github token to be used for docker login'
    required: true
  snyk-token:
    description: 'Snyk access token'
    required: true
  registry-url:
    description: 'Registry url of the docker image to be scanned'
    required: true
  image-tag:
    description: 'Image tag to be scanned'
    required: true
  continue-on-error:
    description: 'Whether to continue the execution if the scan fails'
    default: false
  language:
    description: php / node / python
    required: true

runs:
  using: 'composite'
  steps:
    - uses: hipagesgroup/actions/lw-scanner-action@master
      name: Scan container images for vulnerabitilies using Lacework
      with:
        # Your Lacework account name. For example, if your login URL is mycompany.lacework.net, the account name is mycompany.
        LW_ACCOUNT_NAME: hipagesgroup
        # Authorization token. Copy and paste the token from the inline scanner integration created in the Lacework console.
        LW_ACCESS_TOKEN: ${{ inputs.lacework-token }}
        # Name of the container image you want to scan, for example, `node`.
        IMAGE_NAME: ${{ inputs.registry_url }}/${{ github.repository }}
        # Tag of the container image you want to scan, for example, `12.18.2-alpine`.
        IMAGE_TAG: ${{ inputs.image-tag }}
        # Also scan software packages. (Default: true)
        SCAN_LIBRARY_PACKAGES: true
        # Save results to Lacework. (Default: false)
        SAVE_RESULTS_IN_LACEWORK: true
        # Saves the evaluation report as a local HTML file. (Default: false)
        SAVE_BUILD_REPORT: false
        # Specify custom file name for the HTML evalutation report, by default the name is OS_TYPE-IMAGE_DIGEST_SHA256.html.
        BUILD_REPORT_FILE_NAME: myreport.html
        # Fail the build of vulnerabilities are discovered according to the threshold. (Default: true)
        FAIL_BUILD: ${{ inputs.continue-on-error }}
        # Severity threshold that will fail the build: info, low, medium, high, critical, fixable. (Default: medium)
        SEVERITY_THRESHOLD: medium
        # Use the Lacework policy managed feature (beta). If enabled this overwrites `FAIL_BUILD`and `SEVERITY_THRESHOLD`. (Default: false)
        USE_POLICY: false
        DOCKER_REGISTRY: ${{ inputs.registry_url }}
        DOCKER_USERNAME: hip-infra
        DOCKER_PASSWORD: ${{ inputs.github-token }}

    - name: Run Snyk to check for vulnerabilities
      if: ${{ inputs.language == 'node' }}
      uses: snyk/actions/node@master
      continue-on-error: ${{ inputs.continue-on-error }}
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}

    - name: Run Snyk to check for vulnerabilities
      if: ${{ inputs.language == 'python' }}
      uses: snyk/actions/python$@master
      continue-on-error: ${{ inputs.continue-on-error }}
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}

    - name: Run Snyk to check for vulnerabilities
      if: ${{ inputs.language == 'php' }}
      uses: snyk/actions/php@master
      continue-on-error: ${{ inputs.continue-on-error }}
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
