name: Build Scan and Publish
description: Build Scan and Publish a container to ECR

inputs:
  aws-access-key-id:
    description: AWS Acces key id
    required: true
  aws-secret-access-key:
    description: AWS Secret key id
    required: true
  aws-region:
    description: AWS Region
    required: true
  github-token:
    required: true

outputs:
  container_repository:
    description: Respository of the newly built image
    #value: ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}
    value: "test"
  container_tag:
    description: Tag of the newly built image
    #value: ${{ github.sha }}
    value: "test"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ inputs.aws-access-key-id }}
    #     aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
    #     aws-region: ${{ inputs.aws-region }}

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    - name: Log in to Github Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: hip-ci
        password: ${{ inputs.github-token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # - name: Cache Docker layers
    #   uses: actions/cache@v2
    #   with:
    #     path: /tmp/.buildx-cache
    #     key: ${{ runner.os }}-buildx-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-buildx-

    # - name: Build, tag, and push image ECR
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     pull: false
    #     push: true
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max
    #     tags: ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest,${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}

    - name: Build, tag, and push image GHCR
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        pull: false
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    # - name: Move cache
    #   run: |
    #     rm -rf /tmp/.buildx-cache
    #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    #   shell: bash
    
    # - name: Container scan
    #   uses: Azure/container-scan@v0
    #   with:
    #     image-name: ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}


