name: Build Scan and Publish
description: Build Scan and Publish a container to Container registry

inputs:
  registry:
    # ghcr or ecr
    description: Container registry type ('ecr' or 'ghcr')
    required: true
  registry_url:
    description: Container registry url (eg. ghcr.io)
    required: true

  # ECR settings
  aws-access-key-id:
    description: AWS access key ID
    required: false
  aws-secret-access-key:
    description: AWS secret key
    required: false
  aws-region:
    description: AWS Region
    required: false

  # GHCR token
  github-token:
    description: GITHUB_TOKEN
    default: ${{ github.token }}
    required: false
  npm-token:
    description: NPM PAT to use yarn hipagesgroup packages
    required: false

  # Lacework scan
  lw-access-token:
    description: Lancework access token
    required: false

  scan-docker-image:
    description: Set to true to enable container scanner
    required: false

  build-args:
    description: Buildx build-args
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        grep -q @hipagesgroup yarn.lock && echo //npm.pkg.github.com/:_authToken=${{ inputs.npm-token }} >> .npmrc || true
      if: ${{ inputs.npm-token}}
      shell: bash

    - name: Log in to Github Container registry
      uses: docker/login-action@v2
      if: ${{ inputs.registry == 'ghcr' }}
      with:
        registry: ${{ inputs.registry_url }}
        username: hip-ci
        password: ${{ inputs.github-token }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ inputs.registry == 'ecr' }}
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ github.repository }}
          ${{ inputs.registry_url }}/${{ github.repository }}
        tags: |
          # ensure backwards compatibility
          type=raw,value=${{ env.CI_SHA_SHORT }}
          # set latest tag for default branch
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=branch
          type=ref,event=pr
          type=sha

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      if: ${{ inputs.registry == 'ecr' }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build, tag, and push image GHCR
      uses: docker/build-push-action@v3
      if: ${{ inputs.registry == 'ghcr' }}
      with:
        context: .
        file: ./Dockerfile
        pull: false
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}

    - name: Build, tag, and push image ECR
      uses: docker/build-push-action@v2
      if: ${{ inputs.registry == 'ecr' }}
      with:
        context: .
        file: ./Dockerfile
        pull: true
        push: true
        cache-from: type=registry,ref=${{ inputs.registry_url }}/${{ github.repository }}:latest
        cache-to: type=inline
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}

    - uses: hipagesgroup/actions/lw-scanner-action@master
      name: Scan container images for vulnerabitilies using Lacework
      if: ${{ inputs.scan-docker-image }}
      with:
        # Your Lacework account name. For example, if your login URL is mycompany.lacework.net, the account name is mycompany.
        LW_ACCOUNT_NAME: hipagesgroup
        # Authorization token. Copy and paste the token from the inline scanner integration created in the Lacework console.
        LW_ACCESS_TOKEN: ${{ inputs.lw-access-token }}
        # Name of the container image you want to scan, for example, `node`.
        IMAGE_NAME: ${{ inputs.registry_url }}/${{ github.repository }}
        # Tag of the container image you want to scan, for example, `12.18.2-alpine`.
        IMAGE_TAG: ${{ env.CI_SHA_SHORT }}
        # Also scan software packages. (Default: true)
        SCAN_LIBRARY_PACKAGES: true
        # Save results to Lacework. (Default: false)
        SAVE_RESULTS_IN_LACEWORK: true
        # Saves the evaluation report as a local HTML file. (Default: false)
        SAVE_BUILD_REPORT: false
        # Specify custom file name for the HTML evalutation report, by default the name is OS_TYPE-IMAGE_DIGEST_SHA256.html.
        BUILD_REPORT_FILE_NAME: myreport.html
        # Fail the build of vulnerabilities are discovered according to the threshold. (Default: true)
        FAIL_BUILD: false
        # Severity threshold that will fail the build: info, low, medium, high, critical, fixable. (Default: medium)
        SEVERITY_THRESHOLD: medium
        # Use the Lacework policy managed feature (beta). If enabled this overwrites `FAIL_BUILD`and `SEVERITY_THRESHOLD`. (Default: false)
        USE_POLICY: false
        DOCKER_REGISTRY: ${{ inputs.registry_url }}
        DOCKER_USERNAME: hip-infra
        DOCKER_PASSWORD: ${{ inputs.github-token }}
