name: Build Scan and Publish
description: Build Scan and Publish a container to ECR

inputs:
  aws-access-key-id:
    description: AWS Acces key id
    required: true
  aws-secret-access-key:
    description: AWS Secret key id
    required: true
  aws-region:
    description: AWS Region
    required: true

outputs:
  ecr_repository:
    description: ECR Respository of the newly built image
    value: ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build, tag, and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        #pull: true
        push: true
        cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest
        cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest,mode=min
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}
    
    - name: Container scan
      uses: Azure/container-scan@v0
      with:
        image-name: ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}

