name: Lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  prettier:
    runs-on: ubuntu-latest

    # don't run this on the master branch
    if: github.ref != 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{yml,yaml}
          only_changed: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1
        with:
          warnings: false
