name: Run Python  workflow 

on:
  workflow_call:

jobs:
  dependency-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: pip cache
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ env.pythonLocation }}-
      - name: Install requirements
        run: |
          pip install --upgrade --upgrade-strategy eager -r requirements.txt -e .
        if: steps.pip-cache.outputs.cache-hit != 'true'
      
  run-unit-test:
    runs-on: ubuntu-latest
    needs: dependency-cache
    name: Run Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
      
      