name: Run nodeJs  workflow 

on:
  workflow_call:

jobs:
  dependency-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - run: yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

  run-unit-test:
    runs-on: ubuntu-latest
    needs: dependency-cache
    name: Run Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run tests
        run: yarn test:cov
      
      - name: Upload test coverage file for sonar-scan
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/

  run-integration-tests:
    runs-on: ubuntu-latest
    needs: dependency-cache
    name: Run integration tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run e2e tests
        run: yarn test:e2e