name: Run PHP  workflow 

on:
  workflow_call:

jobs:
  dependency-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - run: yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'