name: "setup sonarcloud"
description: "Setup SonarCloud repository"
author: ""
inputs:
  sonar_token:
    description: SonarCloud token
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "plus-circle"
  color: "green"
